# Challenge #3: Running Averages

>We hope you enjoyed last week's challenge. For the third challenge, let’s look at creating 3 and 6 month running averages.

>The goal is to **create 3 and 6 month running averages for the values contained in columns: c.LK98, p.LK98, c.1K, p.1K, c.NLP3, and p.NLP3. Create the averages by RM Category.** 

>**Update:** As of 9/20/19, the start and solution files were updated.  Your solutions may not look like those posted by Community members prior to this date.

In [3]:
import pandas as pd
# import and preview output
output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output

       RecordID  Year  Month             Name    Value
0             1  2009      1      RM Category    10 rm
1             1  2009      1           C.LK98      218
2             1  2009      1           P.LK98  1178948
3             1  2009      1             C.1K       56
4             1  2009      1             D.1K   319316
...         ...   ...    ...              ...      ...
25987      1368  2014     12  Input_#3_C_LK98        0
25988      1368  2014     12  Input_#3_C_NLP3        0
25989      1368  2014     12    Input_#3_D_1K        0
25990      1368  2014     12  Input_#3_P_LK98        0
25991      1368  2014     12  Input_#3_P_NLP3        0

[25992 rows x 5 columns]

In [4]:
# import and preview input
input = pd.read_csv('input.csv', index_col = False)
df = pd.DataFrame(input)
df

,RM Category,Year,Month,C.LK98,P.LK98,C.1K,D.1K,C.NLP3,P.NLP3
0,10 rm,2009,1,218.0,1178948.0,56.0,319316.0,162.0,859632.0
1,10 rm,2009,2,200.0,1066974.0,44.0,248806.0,156.0,818168.0
2,10 rm,2009,3,272.0,1399758.0,52.0,285730.0,220.0,1114028.0
3,10 rm,2009,4,178.0,996182.0,42.0,235730.0,136.0,760452.0
4,10 rm,2009,5,200.0,1117158.0,60.0,333908.0,140.0,783250.0
...,...,...,...,...,...,...,...,...,...
1363,75 rm,2014,8,NaN,NaN,NaN,NaN,NaN,NaN
1364,75 rm,2014,9,NaN,NaN,NaN,NaN,NaN,NaN
1365,75 rm,2014,10,NaN,NaN,NaN,NaN,NaN,NaN
1366,75 rm,2014,11,NaN,NaN,NaN,NaN,NaN,NaN
1367,75 rm,2014,12,NaN,NaN,NaN,NaN,NaN,NaN